[tox]
envlist = py310,py311,py312,py313

[testenv]
usedevelop = True
extras = tests
commands =
    python -V
    pytest

[gh-actions]
python =
    3.10: py310, mypy
    3.11: py311
    3.12: py312
    3.13: py313